build:
    image: "docker:stable"
    services:
        - "docker:dind"
    stage: "build"
    script:
        - "docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/ubuntu-sshd/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/dev/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/dev-lang/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/dev-lang-java/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/dev-dl/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/irssi/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/rtorrent/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/ubuntu-base/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/squid/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/squid-open/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/gollum/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.11-${CI_COMMIT_SHA:0:8}"
