build:
    image: "docker:stable"
    services:
        - "docker:dind"
    stage: "build"
    script:
        - "docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest dockerfiles/gitlab/ubuntu-sshd/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-sshd:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/dev:latest dockerfiles/gitlab/dev/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/dev:latest registry.gitlab.com/gissehel/docker-gissehel-images/dev:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/dev:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/dev:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang:latest dockerfiles/gitlab/dev-lang/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang:latest registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang-java:latest dockerfiles/gitlab/dev-lang-java/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang-java:latest registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang-java:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang-java:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/dev-lang-java:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/dev-dl:latest dockerfiles/gitlab/dev-dl/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/dev-dl:latest registry.gitlab.com/gissehel/docker-gissehel-images/dev-dl:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/dev-dl:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/dev-dl:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/irssi:latest dockerfiles/gitlab/irssi/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/irssi:latest registry.gitlab.com/gissehel/docker-gissehel-images/irssi:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/irssi:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/irssi:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/rtorrent:latest dockerfiles/gitlab/rtorrent/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/rtorrent:latest registry.gitlab.com/gissehel/docker-gissehel-images/rtorrent:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/rtorrent:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/rtorrent:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-base:latest dockerfiles/gitlab/ubuntu-base/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-base:latest registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-base:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-base:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/ubuntu-base:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/squid:latest dockerfiles/gitlab/squid/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/squid:latest registry.gitlab.com/gissehel/docker-gissehel-images/squid:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/squid:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/squid:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/squid-open:latest dockerfiles/gitlab/squid-open/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/squid-open:latest registry.gitlab.com/gissehel/docker-gissehel-images/squid-open:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/squid-open:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/squid-open:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker build -t registry.gitlab.com/gissehel/docker-gissehel-images/gollum:latest dockerfiles/gitlab/gollum/"
        - "docker tag registry.gitlab.com/gissehel/docker-gissehel-images/gollum:latest registry.gitlab.com/gissehel/docker-gissehel-images/gollum:1.13-${CI_COMMIT_SHA:0:8}"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/gollum:latest"
        - "docker push registry.gitlab.com/gissehel/docker-gissehel-images/gollum:1.13-${CI_COMMIT_SHA:0:8}"
